### ISSUE TITLE
Language changes only after restart

### ISSUE THREAD

**Issue by Adaptivity** [TheCricket/Chisel-2#104]
If you change language in-game you should restart game for applying changes. It's pretty minor issue but it should be fixed.

**Comment by warlordjones** [comment]
That doesn't sound like our issue, off the top of my head. I'll investigate further sometime

**Comment by Adaptivity** [comment]
So, what causes it? Other mods changing language almost instantly. You can try to reproduce it yourself: 1) Enter the world. 2) Change language to different that Chisel supports. 3) See that Chisel blocks and tooltips still in English.

**Comment by warlordjones** [comment]
Hmmmmm, this needs further investigation then

**Comment by Choonster** [comment]
The issue might be that you're translating the descriptions as you register each variation in ModBlocks. To allow language changes to take effect immediately, you probably want to use unlocalised descriptions for each variation and then translate the description in ItemCarvable#addInformation.

Block names themselves should change languages without issue since you're just using Block#setBlockName from CarvableHelper.

**Comment by Adaptivity** [comment]
Yes, names changes their translation immediately.

**Comment by warlordjones** [comment]
Ok, I'll look into doing them like @Choonster suggested. Or I would, except I got booted off the team...

**Comment by tterrag1098** [comment]
Just fixed this, @Choonster's assessment was completely right.
