### ISSUE TITLE
Hex plating without pale overlay

### ISSUE THREAD

**Issue by Aedaeum** [TheCricket/Chisel-2#167]
![black](https://cloud.githubusercontent.com/assets/2054218/5835372/8b7f1a32-a11c-11e4-8083-98b3a5df994b.png)![orange](https://cloud.githubusercontent.com/assets/2054218/5835239/057fe994-a11b-11e4-9aab-1054f2034b5f.png)![pink](https://cloud.githubusercontent.com/assets/2054218/5835243/0ddc9682-a11b-11e4-889b-3cd8964fdfd3.png)![lime](https://cloud.githubusercontent.com/assets/2054218/5835240/09b8cfda-a11b-11e4-9fd3-2b31e4a5c8cd.png)

With images like above, it would be nice to have the option to use them. The new anim and overlay completely circumvent the texture color, making them terribly pale.

My first question is, could you make two recipes, one for overlay/anim and one for static-image hex plating?

The second questions is, is it possible to simply allow the texture color to bleed through instead of forcing a color draw? I understand this might be a little problematic since they're supposed to "glow".

I would at the very least like to see a recipe for static hex plating textures. I really love these blocks, so I hope something can be done here.

Thanks.

**Comment by CptSpaceToaster** [comment]
1.) I'm not a huge fan of multiple recipes for a very similar block.  It can easily confuse a player who doesn't understand the difference between each block, and uses extra block ID's when they aren't absolutely necessary.

2.) Yes it's somewhat possible, but the color overlay texture wouldn't be drawn in a second step, so you'd lose the cool pattern that glows through, as the second step ignores the lightmap.

I think number 2.) is basically asking for a hook into the blocks renderer, and then Chisel would simply pass through an option from the config file.  Something along the lines of "doHexblockOverlay=true".

Since that will not make the overlay texture ignore the lightmap, the hex block will lose the overlay that's always visible, even at night or in a dark cave... so it's not an ideal solution, but it's workable.  

Another more open ended solution might extend 16 RGB values to the config file, and then an artist could supply a new base texture, and a new over lay texture, and that would allow you to color them to your satisfaction.  You wouldn't have to generate 16 images, and users could have a bit more control over the process.

Side note, the brighter the overlay texture, the brighter the colors will be.  It just so happens that the RGB values coming from minecraft's item dye class aren't very saturated, so you can't get much out of them.  Setting your overlay to pure white will draw the pure RGB values we get from itemDye class.  When I get a chance, I'll look at extending a color configuration to the config files.  This sounds like the most ideal solution, but I'd love to hear your opinion on the matter.

**Comment by Aedaeum** [comment]
I completely agree that confusing users isn't a good idea.

I like the idea of a doHexblockOverlay boolean. I assume if you did this, you would implement the full textures again, instead of just the overlay and base.

Your last solution sounds very promising, however you make it sound like we're dependent on the dye saturation. If you're allowing us control over the full RGB spectrum, wouldn't that make the dye color a moot point? The whole idea here is that we have access to vibrant colors again or anything in between since we'll have control over it. 

If we'll be able to achieve the same vibrancy as the images I previewed above, then I'm all for this solution :)

**Comment by CptSpaceToaster** [comment]
Currently, yes... we depend on the color values in the itemDye class, which aren't very saturated.  If we follow through with the second solution, we should have the best of both worlds, albeit, a slightly larger set of configurations...

Then, you could have any brightness you want, based on how bright the greyscale overlay texture is, and you could have any color/saturation you wanted, based on colors read from the configs.

I'm not going to settle for "non-glow" hex blocks :)

**Comment by Aedaeum** [comment]
Haha, okay. That sounds exactly like what I wanted.

Thanks for your work on this, I very much appreciate it :)

**Comment by Aedaeum** [comment]
Oh as a followup, I was wondering why you don't go the route of how Azanor does it with his infused stone?

**Comment by CptSpaceToaster** [comment]
I added them in, you should see this in the next release

**Comment by Drullkus** [comment]
"I should note that I don't mind losing the glow if it means I get to see the textures as they were intended by the artist."

I intended it to be glowy... :P

**Comment by CptSpaceToaster** [comment]
For clarity: The glow was not compromised.

And yes... the big selling point of Hex blocks and Antiblocks were to glow without being effected by the lightmap.

**Comment by tterrag1098** [comment]
Yeah I still don't really get this issue. Is it basically saying "I don't
like the textures"? If so...resource packs.

**Comment by CptSpaceToaster** [comment]
@tterrag1098 The issue is that there isn't a texture to change.  If you didn't like the red, you had NO CHOICE... the red was drawn from fields in the Item.dye class, and the user couldn't make color adjustments, because hex blocks are made out of a base texture, and a greyscale overlay that is colored in the renderer.

I added 16 colors to the config file, and then they are read and stored as ints for use in the glow renderer.

Now, you can change the red overlay to be more saturated, or pastel, based on the value in the config.

**Comment by tterrag1098** [comment]
Sure I guess, but that still just boils down to "I don't like the look of
this." You don't see bug reports on the MC tracker about people not liking
the colors of wool, that wouldn't make sense.

**Comment by Drullkus** [comment]
@tterrag1098 That is the point of texture packs. But the color isn't controlled by texture pack... By code. It at least gives users wiggle room. No harm in it, right?

**Comment by Aedaeum** [comment]
You're amazing @CptSpaceToaster 

Thanks :)
