### ISSUE TITLE
Should we make Antiblocks glow?

### ISSUE THREAD

**Issue by Drullkus** [TheCricket/Chisel-2#169]
Should we make the Antiblocks glow at 15 brightness? 

Additionally, I think@CptSpaceToaster could do some magic and insert the colored lights API :)

**Comment by CptSpaceToaster** [comment]
It can go either way... I think the best thing to do would be to make antiblocks "non-solid" or whatever that weird property was, that stops monsters from spawning on them... but that may have adverse effects (wouldn't be able to place torches on them anymore I think... I don't fully remember)

I'd rather NOT give them a lightvalue, simply because it's not necessary at the moment, and we don't need to stress the lighting engine with castles/mazes built entirely out of light producing blocks.  But I do want to address the fact that monsters can still spawn on them (and bats... bats are annoying)

The colored lights API wouldn't look quite right, because the blocks disable the lightmap as they are drawn... meaning that all of the blocks around them would be colored accordingly, but the antiblocks themselves wouldn't be effected.  A Blue antiblock in Red light wouldn't look purple... everything around it would look purple as the blue light combines with red light.  But the actual block would look peculiar...

**Comment by Mortvana** [comment]
@CptSpaceToaster, I believe this is what you are referring to:

	@Override
	public boolean canCreatureSpawn(EnumCreatureType type, IBlockAccess world, int x, int y, int z) {
		return canSpawn;
	}

**Comment by CptSpaceToaster** [comment]
Does that control bat spawns?

**Comment by Mortvana** [comment]
I have not tested... NEXT TIME ON MORTVANA CODES STUFF, WE BUILD A ROOM OF TF STORAGE BLOCKS TO FIND OUT!!!!

**Comment by CptSpaceToaster** [comment]
![CanNotWait](http://i2.kym-cdn.com/entries/icons/original/000/000/547/1248546877237.png)

**Comment by Drullkus** [comment]
xD

**Comment by warlordjones** [comment]
I'd say that we've come to a consensus on the answer being no - closing issue for tidiness.
