### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by soundlogic2236** [TheCricket/Chisel-2#172]
I'm helping with modtweaker2, and we think it would be nice if we could add the ability to work with the chisel2 api. Unfortunately, it seems there isn't a good way to REMOVE something as chisel-able, which creates issues with the attempts at reversible operations used in minetweaker. If the API could be enhanced to add some way to handle this it would be greatly appreciated.

**Comment by TheCricket** [comment]
If people are making packs and writing a script to remove blocks from chisel, it would be a lot simpler to just disable them in the config. Every block in chisel is configurable.

**Comment by soundlogic2236** [comment]
For starters, while entire sections of chisel can be disabled, the individual transformations can't be. Secondly, minetweaker prefers each of its operations to be reversible. If someone runs a command to add a transformation, there should be an 'undo' for that operator, otherwise the script reloading and such gets glitchy.

**Comment by warlordjones** [comment]
I'm not sure allowing each block variant to be disabled individually would be viable, not least due to the size increase of the config file, if we were to add a boolean for each variant. A blacklist for certain variants could work, I'm unsure. The second part may need explaining again...

**Comment by soundlogic2236** [comment]
I work with modtweaker. It is an addon to minetweaker to add compatibility with more mods. Minetweaker has commands to do things like change recipes. The user/mod pack creator/whoever creates a script file which lists their changes. So one could do something like recipes.addShapeless(blablabla) and it will add that recipe. I would like to add a function like mods.chisel.addToGroup(group,itemstack). To do so properly, each command is supposed to have an 'undo' function that can be called. So I need to be able to add code which undoes the mods.chisel.addToGroup function. As far as I can tell, such a think isn't currently viable, which is problematic. In addition, having the API have a way to remove things from groups would also permit me to add a mods.chisel.removeFromGroup function (or whatever I wind up calling it).

**Comment by TheCricket** [comment]
I can have you add and subtract but it can only be from your end, you may only subtract your blocks and you may not subtract chisel blocks that are there originally, ok?

**Comment by CptSpaceToaster** [comment]
That's not what he's asking.  Minetweaker is basically a minecraft scripting engine that has access to the ore dictionary, and several other useful things that a mod author might want to configure.  Things like the recipe system, and whatnot.  

In this case, chisel presents a way to obtain items that a mod pack creator may want to restrict.  If we make a certain type of material or block chisel-able, then it might become a problem if it opens up an unintended pathway through the mod-packs progression.

As such, the soundlogic can edit recipes, and available blocks, but once a user gets a block, there's nothing that he can do to stop a player from chiseling one type of block, into a much harder to obtain resource.

Soundlogic appears to be asking for [Mod Tweaker](https://github.com/joshiejack/ModTweaker) Integration (not support) so that a mod-tweaker script could in theory, alter a chisel-able configuration after chisel is loaded.  Additionally, one resource could be added to another chisable configuration (which sounds more useful in this case) and any mod-pack author could assign a new mod, to integrate with Chisel in a cool and unique way.

We are quite far away from just flipping the switch and having this work, much less the amount of time it would take to learn how to integrate mod-tweaker... and debug.

@soundlogic2236: A PR at least starting the ball rolling would be far more beneficial than a issue requesting such a feature, but I can start to look into it for now... (no promises)

Examples of how this feature would be used are found in #170 and #171

**Comment by tterrag1098** [comment]
Adding some API methods to remove variations wouldn't be hard, but it would involve breaking the API (adding methods to existing interfaces)

**Comment by soundlogic2236** [comment]
I am perfectly happy to contribute code, though I'm not familiar with your current chisel setup. I have worked with the minetweaker system though, and contributed code to modtweaker, so I am familiar with how that works. There are two main directions though with minetweaker: 1) Modtweaker adds support using your API, 2) The mod itself (chisel 2 in this case) adds is own system using the minetweaker API. I am available a lot of the time on IRC, including in your channel which might be easier to communicate over.

**Comment by tterrag1098** [comment]
Fixed via 974ceec04323a86c5e47979877e43655377f96fb
