### ISSUE TITLE
visually dissapearing blocks

### ISSUE THREAD

**Issue by Prophious** [TheCricket/Chisel-2#431]
so whenever i play with my GF she uses a lot of chisel blocks, now when there is a large area of them i dont see the blocks anymore, and has an x-ray effect 
![2015-11-10_15 33 21](https://cloud.githubusercontent.com/assets/10149920/11243054/cb82d30e-8dd3-11e5-9cb6-7cd8c56360f7.png)
![2015-11-10_16 37 52](https://cloud.githubusercontent.com/assets/10149920/11243055/cb83089c-8dd3-11e5-9939-dea3b8c383b1.png)

as you can see in the WAILA(top center) there is a block there it is reinforced cobble dirt, however this is not the only block that has this effect for me, some work just fine, while others dont

i am not the host of this map.. my GF is... but the issue is still there irregardless, the only real difference i can think of is the minimap, she uses journey map while i use a liteloader mod of voxel map

is this an issue with Chisel or with video settings..... my current video settings are almost default with optifine settings as well
![2015-11-18_09 17 06](https://cloud.githubusercontent.com/assets/10149920/11244084/ce1af280-8dd9-11e5-9a90-126044247c96.png)
![2015-11-18_09 17 20](https://cloud.githubusercontent.com/assets/10149920/11244083/ce17cd08-8dd9-11e5-8c13-4bab66c3e070.png)
![2015-11-18_09 17 29](https://cloud.githubusercontent.com/assets/10149920/11244085/ce1dd27a-8dd9-11e5-8fc9-dc41f6eb2fba.png)

mods included in pack are as follows:
![mwsnap 2015-11-18 09_47_45](https://cloud.githubusercontent.com/assets/10149920/11244056/aaba4386-8dd9-11e5-9db2-a897f9ef289c.png)

Forge Version is forge-1.7.10-10.13.4.1492

**Comment by TehNut** [comment]
Optifine is causing it. And please, [search](https://github.com/Chisel-2/Chisel-2/issues?q=label%3A%22Optifine+Peasantry%22+is%3Aclosed).

**Comment by Drullkus** [comment]
That 'Optifine Peasantry' label was the best idea ever :)

**Comment by Prophious** [comment]
well i never had any issue with it... and why doesn't not have a problem with optifine, her computer is the same and the only mods that are different are liteloader with voxel map vs journey map

also if it seems to be optifine please state it on forum/curse so this issue will not be repeated in a new issue(or less likely not to be)

so if i take off optifine and it still does it then what?

**Comment by CptSpaceToaster** [comment]
I think you might have "rediscovered" this issue: https://github.com/Chisel-2/Chisel-2/issues/376

**Comment by Prophious** [comment]
ok found out that her optifine does not have multi core rendering enabled..... might be the main cause cause i took her config of optifine and copied over mine.... started minecraft... everything is just fine.... then changed the multi-core chunk loading, restarted minecraft again looked at the blocks and the 2 dirt blocks that were missing on mine were missing again..... this may be the only thing that is causing the problem, so i dont know... with regard to issue #376 if this could be fixed for multi-core chunk support or at least playable completely with OptiFine_1.7.10_HD_U_C1, other versions of optifine before this including normal and lite versions(if they have problems too) may get fixed as well 

i will try to link this and #376 on optifine's github see what they say about it and if they can fix it or collaborative efforts

edit: it seems that optifine is not open source and issues are answered in the forum thread.... not going to bother there... who knows if the author even looks at the forums anymore

edit2: is there a difference from yours and the other chisel mod(http://www.curse.com/mc-mods/minecraft/235279-chisel)? anyways... while using the other chisel mod i got an idea..... well with their mod i can see the blocks, place them but as soon as there is a block update that happens the blocks go x-ray style, the other chisel mod is just a fork of this one... although it seems to have a few things updated.... .anyway... the visual rendering of some blocks is in both mods.... i would like to help all i can, but dont know what to even do at this point...

**Comment by CptSpaceToaster** [comment]
Chisel-2 was maintained by a number of devs, and due to differences in programming idealogy between the repository's owner and another, the project split.  This repo still has most of the old devs recieveing notifications on Github, but there isn't much development here anymore.  This project is now largely symbolic of Chisel, but I don't mind responding to issues if I can help.

Looking at the commit history to `master` will reveal that a commit hasn't been made in a couple a couple months: https://github.com/Chisel-2/Chisel-2/commits/master, however some effort on a `1.8` version has been done by the repo owner recently: https://github.com/Chisel-2/Chisel-2/commits/1.8

The project you referenced named "Chisel" is over here: https://github.com/Chisel-Team/Chisel/commits/1.7/dev and should be considered "more up to date" as far as 1.7.10 is concerned.

It has some more recent effort, and changed owners.  The two look like they are [still working together](https://github.com/Chisel-Team/Chisel/commit/40a54a7e6c7b592d49e0042f00c4fff5ee5ab23c), and you can always drop a line in esper.net's #Chisel for this project, and #ChiselTeam for the new project.

_This information is subject to change, as I wasn't really involved, and only experienced some of the changes second hand.  Do not take this account as 100% fact_

**Comment by Prophious** [comment]
so maybe then post this issue in chisel instead, as it is in that one as well... or its good here?

**Comment by CptSpaceToaster** [comment]
We are serious about the `wont fix` tag.

Any issues with Optifine that are opened up in both projects will be closed.  _Because optifine_

**Comment by Drullkus** [comment]
I made the [`Optifine Peasantry`](https://github.com/Chisel-2/Chisel-2/issues?utf8=✓&q=label%3A%22Optifine+Peasantry%22+) tag for a reason. It is up to the Optifine dev to fix his shit not working with our renderers.
