### ISSUE TITLE
Downloads 404 on Curse

### ISSUE THREAD

**Issue by JumpingSpottedTiger** [TheCricket/Chisel-2#458]
There are no files available for download at http://mods.curse.com/mc-mods/minecraft/225236-chisel-3

**Comment by TehNut** [comment]
Use http://minecraft.curseforge.com/projects/chisel

**Comment by JumpingSpottedTiger** [comment]
Is that not a different mod?

**Comment by TehNut** [comment]
It is an updated version of this one.

**Comment by JumpingSpottedTiger** [comment]
I am confused: The Curse page that houses "Chisel 3" links this github tracker.

The mod that you are recommending points to a different project for issue tracking.

Are you telling me that I was trying to get the wrong mod and that this issue tracker is for your link or are you just suggesting I use a different mod (a fork/continuation) entirely?

**Comment by TehNut** [comment]
Use the fork. Sorry for any confusion.

**Comment by TheCricket** [comment]
There will be files coming for it soon :) My version is still the updated and supported version with a stable 1.9 coming very soon. I had to remove the files because Drullkus the previous artist has been harassing me for 50% of the points when he only has about 10% of the work. By removing the files I will soon be able to just cut him off completely because he no longer has any textures in chisel. I hope this explains it :)

**Comment by TehNut** [comment]
@TheCricket Do not edit or remove my comments again.

**Comment by TheCricket** [comment]
;) I was just making it correct

**Comment by TehNut** [comment]
Silently changing comments to be false does not "make them correct" by any means.

**Comment by TheCricket** [comment]
They are true. My version is still actively updated

**Comment by TehNut** [comment]
Your _1.9_ version, yes. Your 1.7.10 version, however, is not. The last commit was in September. CT's last commit for 1.7.10 was 13 days ago.
