### ISSUE TITLE
Crash when installing new chisel2-2.2.0

### ISSUE THREAD

**Issue by chitown3** [TheCricket/Chisel-2#73]
http://pastebin.com/sGQ2nHLA

Seems like the same issue as here: https://bitbucket.org/ProfMobius/mapwriter_opis/issue/1/crash-with-extra-utilities-10
Apparently your  not following proper texture convention, but I may be wrong

**Comment by ghost** [comment]
Hello,

I know this is old and seems to be labeled as "won't fix" but could it possibly be looked into again? Opis and Chisel are both popular mods and tend to be put into packs together, which leads to an issue with having to profile servers when chisel is installed because opis won't work with it. Below is a pastebin with both chisel and opis being used together and the corresponding crash that occurs.

http://pastebin.com/s8zx8ug9 

Thank you for your time,
Auric

**Comment by TheCricket** [comment]
I have used both together and havent crashed

**Comment by ghost** [comment]
Perhaps I am mistaken and it is another mod that is doing it. I am also able to use chisel and opis on other modpacks but a particular one also seems to crash me. I may have just googled and seen this was a crash between the two mods and that this issue existed but wasn't fix at the time. I will continue my search for the underlying cause.
